services:
  fastapi:
    image: boyeongg/kostopnews-fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - kostopnews-network

  streamlit:
    image: boyeongg/kostopnews-dashboard:latest
    container_name: streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      FASTAPI_URL: http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - kostopnews-network

networks:
  kostopnews-network:
    external: true